server:
  port: 8081
 
spring:
  datasource:
    username: root
    password: Jiangshu123
    url: jdbc:mysql://${DB_HOST:localhost}:3306/customer?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.backend.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug